version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_DB=${SUPABASE_DB}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
